name: Build Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  merge_group:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: clientadvisor-webapp
            dockerfile: ClientAdvisor/App/WebApp.Dockerfile
          - app_name: clientadvisor-azurefunction
            dockerfile: ClientAdvisor/AzureFunction/Dockerfile

    uses: ./.github/workflows/build-docker.yml
    with:
      registry: pslpricicdcontainerreg.azurecr.io
      username: pslpricicdcontainerreg
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: true  # Adjust this logic as necessary
    secrets: inherit
