name: Build Docker Images

on:
  push:
    branches: [main]
    paths:
      - ClientAdvisor/**
      - ResearchAssistant/**
  pull_request:
    branches: [main]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - ClientAdvisor/**
      - ResearchAssistant/**
  merge_group:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app_name: clientadvisor-webapp
            dockerfile: ClientAdvisor/App/WebApp.Dockerfile
            registry: pslpricicdcontainerreg.azurecr.io
            username_secret: DOCKER_USERNAME
            password_secret: DOCKER_PASSWORD
          - app_name: clientadvisor-azurefunction
            dockerfile: ClientAdvisor/AzureFunction/Dockerfile
            registry: pslpricicdcontainerreg.azurecr.io
            username_secret: DOCKER_USERNAME
            password_secret: DOCKER_PASSWORD
          - app_name: researchassistant-webapp
            dockerfile: ResearchAssistant/App/WebApp.Dockerfile
            registry: pslpriracontainerreg.azurecr.io
            username_secret: DOCKER_USERNAME_RESEARCHASSISTANT
            password_secret: DOCKER_PASSWORD_RESEARCHASSISTANT

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: ./.github/workflows/build-docker.yml
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets[matrix.username_secret] }}
          password: ${{ secrets[matrix.password_secret] }}
          app_name: ${{ matrix.app_name }}
          dockerfile: ${{ matrix.dockerfile }}
          push: true  # Adjust this logic as necessary
          secrets: inherit
