name: Build Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app_name: byc-wa-app  # Client Advisor Web App
            dockerfile: 'Persistent-byoai/ClientAdvisor/App/WebApp.Dockerfile'
            folder: 'Persistent-byoai/ClientAdvisor/App'
          - app_name: byc-fn-app  # Client Advisor Azure Function
            dockerfile: 'Persistent-byoai/ClientAdvisor/App/AzureFunction/Dockerfile'
            folder: './ClientAdvisor/AzureFunction'
          - app_name: byai-wa-app  # Research Assistant Web App
            dockerfile: 'Persistent-byoai/ResearchAssistant/App/WebApp.Dockerfile'
            folder: 'Persistent-byoai/ResearchAssistant/App'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in current directory
        run: ls -R

      - name: Build Docker Image
        uses: ./.github/workflows/build-docker.yml
        with:
          registry: pslpricicdcontainerreg.azurecr.io  # Your Azure registry
          username: pslpricicdcontainerreg  # Your Azure username
          app_name: ${{ matrix.app_name }}
          dockerfile: ${{ matrix.dockerfile }}
          folder: ${{ matrix.folder }}
          push: true
