name: Build ClientAdvisor Docker Images

on:
  push:
    branches: [main]
    paths:
      - ClientAdvisor/**
  pull_request:
    branches: [main]
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - ClientAdvisor/**
  merge_group:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: clientadvisor-webapp
            dockerfile: ClientAdvisor/App/WebApp.Dockerfile
            password_secret: DOCKER_PASSWORD
          - app_name: clientadvisor-azurefunction
            dockerfile: ClientAdvisor/AzureFunction/Dockerfile
            password_secret: DOCKER_PASSWORD

    uses: ./.github/workflows/build-docker.yml
    with:
      registry: pslpricicdcontainerreg.azurecr.io
      username: pslpricicdcontainerreg
      password_secret: ${{ matrix.password_secret }}
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: true  # Adjust this logic as necessary
    secrets: inherit
