name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'ClientAdvisor/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ClientAdvisor/**'
  workflow_run:
    workflows: ["CI-Validate Deployment-Client Advisor"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Images
        uses: ./.github/workflows/build-docker-image.yml
        with:
          folder: ClientAdvisor/App  # Specify the folder directly

      - name: Notify Slack
        if: always()
        run: |
          STATUS=$(if [[ ${{ job.status }} == 'success' ]]; then echo "SUCCESS"; else echo "FAILURE"; fi)
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"CI/CD Pipeline finished with status: $STATUS\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

  validate_deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Call Validate Deployment Workflow
        run: |
          echo "Triggering CI-Validate Deployment-Client Advisor workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/CI-Validate%20Deployment-Client%20Advisor/dispatches" \
            -d '{"ref": "main"}'
